### PR TITLE
Bridge does not translate the `ReplyToAddress` for failed messages and retries 

### LINKED ISSUE #480: Bridge does not translate the `ReplyToAddress` for failed messages and retries
## Description
When transferring a message, the bridge does not translate the `ReplyToAddress` for failed messages and retries scheduled from ServiceControl. 

This causes problems when the message being retried is processed on a different side (e.g. due to endpoint migration) than the side on which the original error happened and the processing endpoint calls the `ReplyTo` method. 

## Symptoms

Messages retried, that are processed on a different side of the bridge from where the error originated, cannot be processed (processing fails) for endpoints that call `ReplyTo`.

## Root cause

The `ReplyToAddress` is not translated by the bridge for error messages and retry messages.

## Steps to reproduce

- Two endpoints A and B on the left side of the bridge, and ServiceControl on the right side of the bridge
- Bridge is configured with ServiceControl on the right side and A, and B on the left side 
- Endpoint A is sending a message B that fails, it is moved to error, transferred by the bridge, and ingested by ServiceControl
- Endpoint B is migrated to the right side, the declaration of B (i.e. `HasEndpoint("A")`) is moved to the right side of the bridge
- The messages is retried,
- Endpoint B does `RepyTo`
- That fails as the `ReplyToAddress` holds A's physical address on the left sideand 

## Workarounds

- When endpoint B has physical instances on only one side of the bridge before the retry happens, users can edit the `ReplyToAddress` and provide A's physical address on the right side. This will not work with stagged migration i.e. when physical instances of B are on both sides of the bridge. In such a case, it's not known upfront on which side of the bridge the message will be re-processed.

#### Partial solution

- [best-effort-replyto-translation](https://github.com/Particular/NServiceBus.MessagingBridge/commits/best-effort-replyto-translation)

### PR DESCRIPTION
**Pull request by tmasternak**
Fixes #480

### CODE REVIEW

File: src/NServiceBus.MessagingBridge/EndpointRegistry.cs [hunk 1]
```diff
@@ -60,16 +63,18 @@ public TargetEndpointDispatcher GetTargetEndpointDispatcher(string sourceEndpoin
...
-        if (targetEndpointAddressMappings.TryGetValue(sourceAddress, out var targetAddress))
+        if (targetEndpointAddressMappings.TryGetValue(sourceAddress, out result.targetAddress))
         {
-            return targetAddress;
+            result.nearestMatch = result.targetAddress;
+            return true;
         }
 
-        var nearestMatch = GetClosestMatchForExceptionMessage(sourceAddress, targetEndpointAddressMappings.Keys);
+        logger.LogWarning($"Could not translate {sourceAddress} address. Consider using `.HasEndpoint()` method to add missing endpoint declaration.");
```
Comment (abparticular) [inline src/NServiceBus.MessagingBridge/EndpointRegistry.cs:74]: I'm not sure if warning should be logged here - won't it lead to duplicate logging of the error in cases where an exception is ultimately thrown?
Can `bestEffort` be used to switch between logging/throwing in `TransformAddressHeader`?

File: src/NServiceBus.MessagingBridge/IEndpointRegistry.cs [hunk 2]
```diff
@@ -2,7 +2,7 @@
 {
     TargetEndpointDispatcher GetTargetEndpointDispatcher(string sourceEndpointName);
 
-    string TranslateToTargetAddress(string sourceAddress);
+    bool TryTranslateToTargetAddress(string sourceAddress, out (string targetAddress, string nearestMatch) result);
```
Comment (tmasternak) [inline src/NServiceBus.MessagingBridge/IEndpointRegistry.cs:5]: Let's instead of tuple return the best match

File: src/NServiceBus.MessagingBridge/MessageShovel.cs [hunk 3]
```diff
@@ -46,8 +46,13 @@ public async Task TransferMessage(TransferContext transferContext, CancellationT
...
                 //to the correct queue/transport on the other side
 
-                //We _do not_ transform the ReplyToAddress header
                 TransformAddressHeader(messageToSend, targetEndpointRegistry, FaultsHeaderKeys.FailedQ);
+
+                //Try to translate the ReplyToAddress, this is needed when e.g.:
+                // 1. An endpoint is migrated to the ServiceControl side before this messages is retried
+                // 2. An endpoint has physical instances on both sides (migration phase) and when retried
+                //    this message can be processed either on one or the other side of the bridge
+                TransformAddressHeader(messageToSend, targetEndpointRegistry, Headers.ReplyToAddress, bestEffort: true);
```
Comment (tmasternak) [inline src/NServiceBus.MessagingBridge/MessageShovel.cs:55]: Instead of paramter use the `Try` patter and have two methods

Comment (tmasternak) [reply src/NServiceBus.MessagingBridge/MessageShovel.cs:55]: Ended up with `throwOnError` instead of `bestEffort`

**Review by abparticular — APPROVED** [review]

**Review by NChaganlal — APPROVED** [review]
